.TH SLUGIFY "1" "June 2016" "slugify 1.2.0" "User Commands"
.SH NAME
slugify \- Python slugify application that handles unicode
.SH SYNOPSIS
.B slugify TEXTTOSLUGIFY
.SH DESCRIPTION
slugify is a Python slugifying application that handles unicode. 
.SH EXAMPLES
"slugify This is a test ---" returns "this-is-a-test"
